name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install yasm
        if: matrix.os == 'windows-latest'
        run: curl -L -o 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\yasm.exe' http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
      - name: Build codecs
        env:
          CIBW_BEFORE_BUILD: scripts/build-codecs /tmp/vendor
          CIBW_BEFORE_BUILD_WINDOWS: scripts\build-codecs.bat C:\cibw\vendor
          CIBW_BUILD: cp38-*
          CIBW_TEST_COMMAND: python -c "import dummy"
        run: |
          pip install cibuildwheel
          cibuildwheel --output-dir output
          rm -f output/*.whl
        shell: bash
      - name: Upload codecs
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output/
